# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
 ${{ if eq( variables['Build.SourceBranchName'], 'main' ) }}: 
    tag: |
      $(Build.BuildId)
      latest 
  ${{ if ne( variables['Build.SourceBranchName'], 'main' ) }}: 
    tag: '$(Build.BuildId)'
  
  repositoryName: 'jasase/ApplicationInsightsAvailabilityAgent'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      displayName: Build docker image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(repositoryName)'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/src/ApplicationInsightsAvailabilityAgent/Dockerfile'
        buildContext: 'src'
        tags: '$(tag)'

    - task: Docker@2
      displayName: Push docker image
      condition: 'and(succeeded(), eq(variables['Build.SourceBranch'], 'main'))'
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(repositoryName)'
        command: 'push'
        tags: '$(tag)'